# -*- encoding=utf8 -*-
__author__ = "XXu"

from airtest.core.api import *
from poco.proxy import UIObjectProxy
from poco.drivers.android.uiautomation import AndroidUiautomationPoco
from airtest.core.api import device
auto_setup(__file__)
poco = AndroidUiautomationPoco()

# #如果不需要多台机器联合测试，就可以使用#在代码的最前面给代码屏蔽掉
# #设置多机联合执行验证
print(G.DEVICE_LIST)
dev1 = connect_device("Android://127.0.0.1:5037/103cdef4")  # 第一台手机
dev2 = connect_device("Android://127.0.0.1:5037/R58N12E57DV")  # 第二台手机
set_current("10历史的进程哦收到i3cdef4")


#这里就是检查设置页面的元素是否完备
#抓取标识符图
screen70 = Template(r"tpl1716884310488.png", record_pos=(0.002, -0.416), resolution=(1080, 2400))
#threshold值修改，匹配度到100%
screen100 = Template(r"tpl1716884341585.png",threshold=1, record_pos=(0.007, -0.401), resolution=(1080, 2400))
assert_not_exists(screen100,"检查配置模式图片内容匹配度是100%时存在")
sleep(1.0)

poco("com.philips.ph.homecare:id/settings_support_id").click()
poco("转到上一层级").click()
#通知的功能性验证
poco("com.philips.ph.homecare:id/settings_notification_id").click()
poco(desc="污染通知").click()
poco(desc="污染通知").click()
poco(desc="Notification").click()
poco(text="未使用").click()
poco("android:id/switch_widget").click()
poco("android:id/switch_widget").click()
poco("向上导航").click()
#设备设置
poco("com.philips.ph.homecare:id/settings_device_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/appliance_item_layout_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/philipsSetting_name_id").click()
text("air")
poco("com.philips.ph.homecare:id/menu_done_id").click()
poco("转到上一层级").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/settings_device_id").click()
poco("com.philips.ph.homecare:id/appliance_item_layout_id").click()
#首选指数
poco("com.philips.ph.homecare:id/philipsSetting_preferred_id").click()
poco(text="PM2.5").click()
sleep(1.0)
#创建计划
poco("com.philips.ph.homecare:id/philipsSetting_schedule_id").click()
sleep(1.0)

poco("com.philips.ph.homecare:id/schedule_empty_create_btn").click()
poco("com.philips.ph.homecare:id/schedule_done_btn").click()
poco("com.philips.ph.homecare:id/schedule_item_layout_id").swipe([-0.9,-0.1])
sleep(1.0)
poco("com.philips.ph.homecare:id/schedule_item_delete_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/schedule_calendar_btn").click()
poco("转到上一层级").click()
#第三方服务
poco("com.philips.ph.homecare:id/philipsSetting_services_id").click()
poco("com.philips.ph.homecare:id/third_party_service_icon").click()
sleep(4.0)
poco("com.sec.android.app.sbrowser:id/custom_tab_toolbar_close_icon").click()
sleep(1.0)
poco("转到上一层级").click()

#个性化
poco("com.philips.ph.homecare:id/philipsSetting_personalize_id").click()
poco(text="粉尘/细尘").click()
poco(text="甲醛").click()
poco(text="垃圾异味").click()
poco(text="雾霾/烟雾/PM2.5").click()
poco(text="汽车/工厂排气").click()
poco(text="烹饪").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
poco(text="6 个月到 2 年").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/philipsSetting_personalize_id").click()
sleep(1.0)
poco(text="粉尘/细尘").click()
poco(text="甲醛").click()
poco(text="垃圾异味").click()
poco(text="雾霾/烟雾/PM2.5").click()
poco(text="汽车/工厂排气").click()
poco(text="烹饪").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
poco(text="不到 6 个月").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
#设备信息
poco("com.philips.ph.homecare:id/philipsSetting_info_id").click()
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/philipsSetting_notification_id").click()
poco("com.philips.ph.homecare:id/device_notification_aqi_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_radio2").click()
poco("com.philips.ph.homecare:id/air_notification_health_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_error_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_error_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_health_switch_id").click()
poco("com.philips.ph.homecare:id/device_notification_aqi_switch_id").click()
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/philipsSetting_support_id").click()
poco("转到上一层级").click()
poco("转到上一层级").click()
poco("转到上一层级").click()
#显示设置
poco("com.philips.ph.homecare:id/settings_display_id").click()
poco("com.philips.ph.homecare:id/display_unit_imperial_btn").click()
poco("com.philips.ph.homecare:id/display_unit_metric_btn").click()
poco("com.philips.ph.homecare:id/display_unit_imperial_btn").click()
poco("com.philips.ph.homecare:id/display_unit_metric_btn").click()
poco("com.philips.ph.homecare:id/display_weather_location").click()
poco("转到上一层级").click()
#切换成英语
poco("com.philips.ph.homecare:id/display_language").click()
poco("android.widget.FrameLayout").child("android.widget.FrameLayout").offspring("android:id/content").offspring("com.philips.ph.homecare:id/language_list_id").child("android.widget.LinearLayout")[16].child("android.widget.RadioButton").click()
poco("com.philips.ph.homecare:id/menu_done_id").click()
poco("android:id/button1").click()
sleep(1.0)

start_app("com.philips.ph.homecare")
sleep(4.0)
#切换回汉语
poco("com.philips.ph.homecare:id/navigation_settings").click()
poco("com.philips.ph.homecare:id/settings_display_id").click()
poco("com.philips.ph.homecare:id/display_language").click()
poco(text="Chinese, Simplified").click()
poco("com.philips.ph.homecare:id/menu_done_id").click()
poco("android:id/button1").click()
start_app("com.philips.ph.homecare")
sleep(4.0)

poco("com.philips.ph.homecare:id/navigation_settings").click()
#同意管理
poco("com.philips.ph.homecare:id/settings_consent_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/consent_cookie_switch").click()
sleep(1.0)
#poco("android:id/button1").click()
poco("com.android.systemui:id/back").click()
还原授权
poco("com.philips.ph.homecare:id/settings_consent_id").click()
poco("com.philips.ph.homecare:id/consent_cookie_switch").click()
poco("android:id/button1").click()
poco("com.android.systemui:id/back").click()
poco("com.philips.ph.homecare:id/settings_permissions_id").click()
poco("com.android.systemui:id/back").click()
#关于
poco("com.philips.ph.homecare:id/settings_about_id").click()
poco("com.philips.ph.homecare:id/about_website_id").click()
sleep(5.0)
poco("com.sec.android.app.sbrowser:id/custom_tab_toolbar_close_icon").click()
poco("com.philips.ph.homecare:id/about_terms_id").click()
sleep(5.0)
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/about_open_source_id").click()
sleep(3.0)
swipe((526,1718),(526,430))
swipe((526,1718),(526,430))
swipe((526,1718),(526,430))
swipe((526,1718),(526,430))
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/about_review_app_id").click()
poco("com.philips.ph.homecare:id/enjoy_sheet_yes").click()
#返回设置的总页面
poco("转到上一层级").click()


#set_current("R58N12E57DV")
#这里就是检查设置页面的元素是否完备
#抓取标识符图
screen70 = Template(r"tpl1716884310488.png", record_pos=(0.002, -0.416), resolution=(1080, 2400))
#threshold值修改，匹配度到100%
screen100 = Template(r"tpl1716884341585.png",threshold=1, record_pos=(0.007, -0.401), resolution=(1080, 2400))
assert_not_exists(screen100,"检查配置模式图片内容匹配度是100%时存在")
sleep(1.0)

poco("com.philips.ph.homecare:id/settings_support_id").click()
poco("转到上一层级").click()
#通知的功能性验证
poco("com.philips.ph.homecare:id/settings_notification_id").click()
poco(desc="污染通知").click()
poco(desc="污染通知").click()
poco(desc="Notification").click()
poco(text="未使用").click()
poco("android:id/switch_widget").click()
poco("android:id/switch_widget").click()
poco("向上导航").click()
#设备设置
poco("com.philips.ph.homecare:id/settings_device_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/appliance_item_layout_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/philipsSetting_name_id").click()
text("air")
poco("com.philips.ph.homecare:id/menu_done_id").click()
poco("转到上一层级").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/settings_device_id").click()
poco("com.philips.ph.homecare:id/appliance_item_layout_id").click()
#首选指数
poco("com.philips.ph.homecare:id/philipsSetting_preferred_id").click()
poco(text="PM2.5").click()
sleep(1.0)
#创建计划
poco("com.philips.ph.homecare:id/philipsSetting_schedule_id").click()
sleep(1.0)

poco("com.philips.ph.homecare:id/schedule_empty_create_btn").click()
poco("com.philips.ph.homecare:id/schedule_done_btn").click()
poco("com.philips.ph.homecare:id/schedule_item_layout_id").swipe([-0.9,-0.1])
sleep(1.0)
poco("com.philips.ph.homecare:id/schedule_item_delete_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/schedule_calendar_btn").click()
poco("转到上一层级").click()
#第三方服务
poco("com.philips.ph.homecare:id/philipsSetting_services_id").click()
poco("com.philips.ph.homecare:id/third_party_service_icon").click()
sleep(4.0)
poco("com.sec.android.app.sbrowser:id/custom_tab_toolbar_close_icon").click()
sleep(1.0)
poco("转到上一层级").click()

#个性化
poco("com.philips.ph.homecare:id/philipsSetting_personalize_id").click()
poco(text="粉尘/细尘").click()
poco(text="甲醛").click()
poco(text="垃圾异味").click()
poco(text="雾霾/烟雾/PM2.5").click()
poco(text="汽车/工厂排气").click()
poco(text="烹饪").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
poco(text="6 个月到 2 年").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/philipsSetting_personalize_id").click()
sleep(1.0)
poco(text="粉尘/细尘").click()
poco(text="甲醛").click()
poco(text="垃圾异味").click()
poco(text="雾霾/烟雾/PM2.5").click()
poco(text="汽车/工厂排气").click()
poco(text="烹饪").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
poco(text="不到 6 个月").click()
poco("com.philips.ph.homecare:id/personalize_questionnaire_next").click()
#设备信息
poco("com.philips.ph.homecare:id/philipsSetting_info_id").click()
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/philipsSetting_notification_id").click()
poco("com.philips.ph.homecare:id/device_notification_aqi_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_radio2").click()
poco("com.philips.ph.homecare:id/air_notification_health_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_error_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_error_switch_id").click()
poco("com.philips.ph.homecare:id/air_notification_health_switch_id").click()
poco("com.philips.ph.homecare:id/device_notification_aqi_switch_id").click()
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/philipsSetting_support_id").click()
poco("转到上一层级").click()
poco("转到上一层级").click()
poco("转到上一层级").click()
#显示设置
poco("com.philips.ph.homecare:id/settings_display_id").click()
poco("com.philips.ph.homecare:id/display_unit_imperial_btn").click()
poco("com.philips.ph.homecare:id/display_unit_metric_btn").click()
poco("com.philips.ph.homecare:id/display_unit_imperial_btn").click()
poco("com.philips.ph.homecare:id/display_unit_metric_btn").click()
poco("com.philips.ph.homecare:id/display_weather_location").click()
poco("转到上一层级").click()
#切换成英语
poco("com.philips.ph.homecare:id/display_language").click()
poco("android.widget.FrameLayout").child("android.widget.FrameLayout").offspring("android:id/content").offspring("com.philips.ph.homecare:id/language_list_id").child("android.widget.LinearLayout")[16].child("android.widget.RadioButton").click()
poco("com.philips.ph.homecare:id/menu_done_id").click()
poco("android:id/button1").click()
sleep(1.0)

start_app("com.philips.ph.homecare")
sleep(4.0)
#切换回汉语
poco("com.philips.ph.homecare:id/navigation_settings").click()
poco("com.philips.ph.homecare:id/settings_display_id").click()
poco("com.philips.ph.homecare:id/display_language").click()
poco(text="Chinese, Simplified").click()
poco("com.philips.ph.homecare:id/menu_done_id").click()
poco("android:id/button1").click()
start_app("com.philips.ph.homecare")
sleep(4.0)

poco("com.philips.ph.homecare:id/navigation_settings").click()
#同意管理
poco("com.philips.ph.homecare:id/settings_consent_id").click()
sleep(1.0)
poco("com.philips.ph.homecare:id/consent_cookie_switch").click()
sleep(1.0)
#poco("android:id/button1").click()
poco("com.android.systemui:id/back").click()
#还原授权
poco("com.philips.ph.homecare:id/settings_consent_id").click()
poco("com.philips.ph.homecare:id/consent_cookie_switch").click()
poco("android:id/button1").click()
poco("com.android.systemui:id/back").click()
poco("com.philips.ph.homecare:id/settings_permissions_id").click()
poco("com.android.systemui:id/back").click()
#关于
poco("com.philips.ph.homecare:id/settings_about_id").click()
poco("com.philips.ph.homecare:id/about_website_id").click()
sleep(5.0)
poco("com.sec.android.app.sbrowser:id/custom_tab_toolbar_close_icon").click()
poco("com.philips.ph.homecare:id/about_terms_id").click()
sleep(5.0)
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/about_open_source_id").click()
sleep(3.0)
swipe((526,1718),(526,430))
swipe((526,1718),(526,430))
swipe((526,1718),(526,430))
swipe((526,1718),(526,430))
poco("转到上一层级").click()
poco("com.philips.ph.homecare:id/about_review_app_id").click()
poco("com.philips.ph.homecare:id/enjoy_sheet_yes").click()
#返回设置的总页面
poco("转到上一层级").click()





